dist: xenial
language: ruby
sudo: true

rvm:
  - 2.1.1
  - 2.5.3
  - 2.6.0

matrix:
  allow_failures:
    - rvm: 2.1.1
    - rvm: 2.6.0

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
  - postgresql
  - redis-server

before_install:
  - cp config/database.yml.sample config/database.yml
  - cp .env.test .env

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - bundle exec rake db:setup
  - bundle exec rspec
