dist: xenial
language: ruby
sudo: true

rvm:
  - 2.1.1
  - 2.5.3
  - 2.6.0

matrix:
  allow_failures:
    - rvm: 2.1.1
    - rvm: 2.6.0

jobs:
  include:
    - stage: db_setup
      name: 'Perform DB setup (with seeds)'
      rvm:
        - 2.5.3
      services:
        - postgresql
        - redis-server
      before_install:
        - cp config/database.yml.sample config/database.yml
      script:
        - bundle exec rake db:setup

    - stage: tests
      name: 'Tests'
      rvm:
        - 2.5.3
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      services:
        - postgresql
        - redis-server
      before_install:
        - cp config/database.yml.sample config/database.yml
        - cp .env.test .env
        - sudo apt-get update
        - sudo apt-get install chromium-chromedriver
      before_script:
        - "export PATH=$PATH:/usr/lib/chromium-browser/"
        - bundle exec rake db:create
        - bundle exec rake db:schema:load
      script:
        - bundle exec rspec

stages:
  - db_setup
  - tests
