dist: xenial
language: ruby
sudo: true

rvm:
  - 2.1.1
  - 2.5.3
  - 2.6.0

matrix:
  allow_failures:
    - rvm: 2.1.1
    - rvm: 2.6.0

addons:
  chrome: stable

services:
  - postgresql
  - redis-server

before_install:
  - cp config/database.yml.sample config/database.yml
  - cp .env.test .env
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - bundle exec rake db:setup
  - bundle exec rspec
